# 端口号
server:
  port: 8080

# Spring配置
spring:
  application:
    # 应用名
    name: news-daily-ranking
  datasource:
    # 配置Druid数据源类型
    type: com.alibaba.druid.pool.DruidDataSource
    # 数据库连接URL，包括数据库名、允许的公开密钥检索、字符编码、禁用SSL、时区设置等
    url: jdbc:mysql://localhost:3306/news_daily_ranking?allowPublicKeyRetrieval=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull
    # 数据库用户名
    username: root
    # 数据库密码
    password: root
    # 数据库驱动类名
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # 初始化连接池时创建的连接数量
      initial-size: 5
      # 连接池最小空闲连接数
      min-idle: 5
      # 连接池最大活跃连接数
      max-active: 30
      # 连接池最大等待时间，单位毫秒
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位毫秒
      min-evictable-idle-time-millis: 300000
      # 验证数据库连接有效的SQL语句
      validation-query: SELECT 1 FROM DUAL
      # 是否在从连接池获取连接前进行检验(建议关闭，影响性能)
      test-while-idle: true
      # 获取连接时执行validationQuery检测连接是否有效(建议关闭，影响性能)
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效(建议关闭，影响性能)
      test-on-return: false
      # 是否开启PSCache（PreparedStatement缓存），默认false
      pool-prepared-statements: false
      # 指定每个连接上PSCache的大小，默认-1表示不限制
      max-pool-prepared-statement-per-connection-size: 0
      # 启用监控统计和日志过滤器
      filters: stat,wall
      # 配置StatFilter的参数，合并SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 是否合并Druid数据源的监控信息
      use-global-data-source-stat: true
      filter:
        wall:
          # 开启Wall过滤器，并指定数据库类型为MySQL
          enabled: true
          db-type: mysql
        stat:
          # 配置StatFilter的数据库类型为MySQL
          enabled: true
          db-type: mysql

  redis:
    # Redis数据库索引
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis连接超时时间（毫秒）
    timeout: 1800000
    # Redis服务器端口
    port: 6379
#    # Redis服务器连接密码
#    password: llf19990319
    # 使用Lettuce连接池时的最大等待时间（-1表示无限制
    lettuce:
      pool:
        max-wait: -1
        # Lettuce连接池的最大空闲连接数
        max-idle: 5
        # Lettuce连接池的最小空闲连接数
        min-idle: 0
        # Lettuce连接池的最大活跃连接数
        max-active: 20
    jedis:
      pool:
        # 使用Jedis连接池时的最小空闲连接数
        min-idle: 8
        # Jedis连接池的最大空闲连接数
        max-idle: 500
        # Jedis连接池的最大活跃连接数
        max-active: 2000
        # Jedis连接池的最大等待时间（毫秒）
        max-wait: 10000
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    mode: HTML

# MyBatis配置：自动映射行为设置为全字段
mybatis:
  configuration:
    auto-mapping-behavior: FULL
    # MyBatis配置：下划线转驼峰命名规则
    map-underscore-to-camel-case: true
    # MyBatis-Plus的Mapper文件位置
    mapper-locations: classpath*:/mybatis/mapper/*.xml

#xxl-job
xxl:
  job:
    open: true
    admin:
      addresses: http://127.0.0.1:12000/xxl-job-admin
    accessToken: default_token
    executor:
      appname: news-daily-ranking
      logpath: /root/logs/xxl-job/jobhandler
      logretentiondays: 30
      address:
      ip:
      port: 9999